services:
  app:
    container_name: chabo-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=v0.0.0+dev
    volumes:
      - persistent-app-volume:/app
    ports:
      - "8080:8080"
      - "6060:6060"
    env_file:
      - .env.dev

  mongo:
    container_name: mongo-server
    image: mongo:6.0.20
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: my_password
      MONGO_INITDB_DATABASE: chabo-api

volumes:
  persistent-app-volume: