services:
  app:
    container_name: chabo-api
    depends_on:
      - postgresql
      - mongodb
    command: >
       sh -c "go run ."
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - VERSION=v0.0.0+dev
    ports:
      - "8080:8080"
      - "6060:6060"
    env_file:
      - .env.dev
  mongodb:
    container_name: mongodb
    image: mongo:8.0.8
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: my_password
      MONGO_INITDB_DATABASE: chabo-api


  postgresql:
    container_name: postgresql
    image: postgres:17.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: chabo-api
    volumes:
      - postgresqldata:/var/lib/postgresql/data 
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:9.2.0
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: my_password
    volumes:
      - pgadmindata:/var/lib/pgadmin
    
volumes:
  mongodata:
  postgresqldata:
  pgadmindata: