version: '3.8'

services:
  app:
    container_name: chabo-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    env_file:
      - .env.dev

  mongo:
    container_name: mongo-server
    image: mongo:6.0.8
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: my_password
      MONGO_INITDB_DATABASE: chabo-api

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: my_password
      ME_CONFIG_MONGODB_URL: mongodb://root:my_password@mongo:27017/