services:
  app:
    container_name: chabo-api
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - VERSION=v0.0.0+dev
    ports:
      - "8080:8080"
      - "6060:6060"
    env_file:
      - /.env.dev
  mongodb:
    container_name: mongodb
    image: mongo:8.0.15
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: my_password
      MONGO_INITDB_DATABASE: chabo-api


  postgresql:
    container_name: postgresql
    image: postgres:17.6
    environment:
      POSTGRES_PASSWORD: my_password