# syntax=docker/dockerfile:1

FROM golang:1.22.0 as build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download 
# Dependency used to build Swagger config
RUN go install github.com/swaggo/swag/cmd/swag@latest
# Dependencies used for static config
RUN go install golang.org/x/tools/gopls@latest
RUN go install github.com/go-delve/delve/cmd/dlv@latest
RUN go install honnef.co/go/tools/cmd/staticcheck@latest
RUN go install golang.org/x/tools/cmd/godoc@latest
RUN go install github.com/segmentio/golines@latest
# https://golangci-lint.run/usage/install/#binaries
RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
RUN go mod vendor 

COPY . .
# Refresh Swagger config
RUN swag init -d ./internal/api/routers,./ -g main_router.go

EXPOSE 8080
