# syntax=docker/dockerfile:1

FROM golang:1.20 as build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download 
RUN go install github.com/swaggo/swag/cmd/swag@latest
COPY . .
RUN ls /app
RUN swag init -d ./internal/api,./ -g router.go

EXPOSE 8080

CMD ["go", "run", "."]
