// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: grpc/v1/boat.proto

package generate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BoatManeuver int32

const (
	BoatManeuver_leaving  BoatManeuver = 0
	BoatManeuver_entering BoatManeuver = 1
)

// Enum value maps for BoatManeuver.
var (
	BoatManeuver_name = map[int32]string{
		0: "leaving",
		1: "entering",
	}
	BoatManeuver_value = map[string]int32{
		"leaving":  0,
		"entering": 1,
	}
)

func (x BoatManeuver) Enum() *BoatManeuver {
	p := new(BoatManeuver)
	*p = x
	return p
}

func (x BoatManeuver) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BoatManeuver) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_v1_boat_proto_enumTypes[0].Descriptor()
}

func (BoatManeuver) Type() protoreflect.EnumType {
	return &file_grpc_v1_boat_proto_enumTypes[0]
}

func (x BoatManeuver) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BoatManeuver.Descriptor instead.
func (BoatManeuver) EnumDescriptor() ([]byte, []int) {
	return file_grpc_v1_boat_proto_rawDescGZIP(), []int{0}
}

type Timestamp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seconds int64 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos   int32 `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_boat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_boat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_grpc_v1_boat_proto_rawDescGZIP(), []int{0}
}

func (x *Timestamp) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Timestamp) GetNanos() int32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

type Boat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name                      string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Maneuver                  BoatManeuver `protobuf:"varint,2,opt,name=maneuver,proto3,enum=grpc.v1.BoatManeuver" json:"maneuver,omitempty"`
	ApproximativeCrossingDate *Timestamp   `protobuf:"bytes,3,opt,name=approximativeCrossingDate,proto3" json:"approximativeCrossingDate,omitempty"`
}

func (x *Boat) Reset() {
	*x = Boat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_boat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Boat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Boat) ProtoMessage() {}

func (x *Boat) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_boat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Boat.ProtoReflect.Descriptor instead.
func (*Boat) Descriptor() ([]byte, []int) {
	return file_grpc_v1_boat_proto_rawDescGZIP(), []int{1}
}

func (x *Boat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Boat) GetManeuver() BoatManeuver {
	if x != nil {
		return x.Maneuver
	}
	return BoatManeuver_leaving
}

func (x *Boat) GetApproximativeCrossingDate() *Timestamp {
	if x != nil {
		return x.ApproximativeCrossingDate
	}
	return nil
}

type BoatNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *BoatNameRequest) Reset() {
	*x = BoatNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_boat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoatNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoatNameRequest) ProtoMessage() {}

func (x *BoatNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_boat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoatNameRequest.ProtoReflect.Descriptor instead.
func (*BoatNameRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_boat_proto_rawDescGZIP(), []int{2}
}

func (x *BoatNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Boats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Forecasts []*Boat `protobuf:"bytes,1,rep,name=forecasts,proto3" json:"forecasts,omitempty"`
}

func (x *Boats) Reset() {
	*x = Boats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_boat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Boats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Boats) ProtoMessage() {}

func (x *Boats) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_boat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Boats.ProtoReflect.Descriptor instead.
func (*Boats) Descriptor() ([]byte, []int) {
	return file_grpc_v1_boat_proto_rawDescGZIP(), []int{3}
}

func (x *Boats) GetForecasts() []*Boat {
	if x != nil {
		return x.Forecasts
	}
	return nil
}

var File_grpc_v1_boat_proto protoreflect.FileDescriptor

var file_grpc_v1_boat_proto_rawDesc = []byte{
	0x0a, 0x12, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x6f, 0x61, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x22, 0x3b, 0x0a,
	0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x61, 0x6e, 0x6f, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x6e, 0x61, 0x6e, 0x6f, 0x73, 0x22, 0x9f, 0x01, 0x0a, 0x04, 0x42,
	0x6f, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x6d, 0x61, 0x6e, 0x65, 0x75,
	0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6f, 0x61, 0x74, 0x4d, 0x61, 0x6e, 0x65, 0x75, 0x76, 0x65, 0x72,
	0x52, 0x08, 0x6d, 0x61, 0x6e, 0x65, 0x75, 0x76, 0x65, 0x72, 0x12, 0x50, 0x0a, 0x19, 0x61, 0x70,
	0x70, 0x72, 0x6f, 0x78, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x76, 0x65, 0x43, 0x72, 0x6f, 0x73, 0x73,
	0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x19, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x78, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x76, 0x65,
	0x43, 0x72, 0x6f, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x65, 0x22, 0x25, 0x0a, 0x0f,
	0x42, 0x6f, 0x61, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x34, 0x0a, 0x05, 0x42, 0x6f, 0x61, 0x74, 0x73, 0x12, 0x2b, 0x0a, 0x09,
	0x66, 0x6f, 0x72, 0x65, 0x63, 0x61, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6f, 0x61, 0x74, 0x52, 0x09,
	0x66, 0x6f, 0x72, 0x65, 0x63, 0x61, 0x73, 0x74, 0x73, 0x2a, 0x29, 0x0a, 0x0c, 0x42, 0x6f, 0x61,
	0x74, 0x4d, 0x61, 0x6e, 0x65, 0x75, 0x76, 0x65, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x6c, 0x65, 0x61,
	0x76, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x69,
	0x6e, 0x67, 0x10, 0x01, 0x32, 0x43, 0x0a, 0x0b, 0x42, 0x6f, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x61, 0x74, 0x12, 0x18,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6f, 0x61, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x42, 0x6f, 0x61, 0x74, 0x22, 0x00, 0x42, 0x14, 0x5a, 0x12, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_v1_boat_proto_rawDescOnce sync.Once
	file_grpc_v1_boat_proto_rawDescData = file_grpc_v1_boat_proto_rawDesc
)

func file_grpc_v1_boat_proto_rawDescGZIP() []byte {
	file_grpc_v1_boat_proto_rawDescOnce.Do(func() {
		file_grpc_v1_boat_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_v1_boat_proto_rawDescData)
	})
	return file_grpc_v1_boat_proto_rawDescData
}

var file_grpc_v1_boat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_v1_boat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_v1_boat_proto_goTypes = []interface{}{
	(BoatManeuver)(0),       // 0: grpc.v1.BoatManeuver
	(*Timestamp)(nil),       // 1: grpc.v1.Timestamp
	(*Boat)(nil),            // 2: grpc.v1.Boat
	(*BoatNameRequest)(nil), // 3: grpc.v1.BoatNameRequest
	(*Boats)(nil),           // 4: grpc.v1.Boats
}
var file_grpc_v1_boat_proto_depIdxs = []int32{
	0, // 0: grpc.v1.Boat.maneuver:type_name -> grpc.v1.BoatManeuver
	1, // 1: grpc.v1.Boat.approximativeCrossingDate:type_name -> grpc.v1.Timestamp
	2, // 2: grpc.v1.Boats.forecasts:type_name -> grpc.v1.Boat
	3, // 3: grpc.v1.BoatService.GetBoat:input_type -> grpc.v1.BoatNameRequest
	2, // 4: grpc.v1.BoatService.GetBoat:output_type -> grpc.v1.Boat
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_grpc_v1_boat_proto_init() }
func file_grpc_v1_boat_proto_init() {
	if File_grpc_v1_boat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_v1_boat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Timestamp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_boat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Boat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_boat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoatNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_boat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Boats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_v1_boat_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_v1_boat_proto_goTypes,
		DependencyIndexes: file_grpc_v1_boat_proto_depIdxs,
		EnumInfos:         file_grpc_v1_boat_proto_enumTypes,
		MessageInfos:      file_grpc_v1_boat_proto_msgTypes,
	}.Build()
	File_grpc_v1_boat_proto = out.File
	file_grpc_v1_boat_proto_rawDesc = nil
	file_grpc_v1_boat_proto_goTypes = nil
	file_grpc_v1_boat_proto_depIdxs = nil
}
