// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: grpc/v1/healthcheck.proto

package generate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	HealthCheckService_CheckHealth_FullMethodName = "/grpc.v1.HealthCheckService/CheckHealth"
	HealthCheckService_WatchHealth_FullMethodName = "/grpc.v1.HealthCheckService/WatchHealth"
)

// HealthCheckServiceClient is the client API for HealthCheckService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthCheckServiceClient interface {
	CheckHealth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	WatchHealth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (HealthCheckService_WatchHealthClient, error)
}

type healthCheckServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthCheckServiceClient(cc grpc.ClientConnInterface) HealthCheckServiceClient {
	return &healthCheckServiceClient{cc}
}

func (c *healthCheckServiceClient) CheckHealth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, HealthCheckService_CheckHealth_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthCheckServiceClient) WatchHealth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (HealthCheckService_WatchHealthClient, error) {
	stream, err := c.cc.NewStream(ctx, &HealthCheckService_ServiceDesc.Streams[0], HealthCheckService_WatchHealth_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &healthCheckServiceWatchHealthClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HealthCheckService_WatchHealthClient interface {
	Recv() (*HealthCheckResponse, error)
	grpc.ClientStream
}

type healthCheckServiceWatchHealthClient struct {
	grpc.ClientStream
}

func (x *healthCheckServiceWatchHealthClient) Recv() (*HealthCheckResponse, error) {
	m := new(HealthCheckResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HealthCheckServiceServer is the server API for HealthCheckService service.
// All implementations must embed UnimplementedHealthCheckServiceServer
// for forward compatibility
type HealthCheckServiceServer interface {
	CheckHealth(context.Context, *Empty) (*HealthCheckResponse, error)
	WatchHealth(*Empty, HealthCheckService_WatchHealthServer) error
	mustEmbedUnimplementedHealthCheckServiceServer()
}

// UnimplementedHealthCheckServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHealthCheckServiceServer struct {
}

func (UnimplementedHealthCheckServiceServer) CheckHealth(context.Context, *Empty) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckHealth not implemented")
}
func (UnimplementedHealthCheckServiceServer) WatchHealth(*Empty, HealthCheckService_WatchHealthServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchHealth not implemented")
}
func (UnimplementedHealthCheckServiceServer) mustEmbedUnimplementedHealthCheckServiceServer() {}

// UnsafeHealthCheckServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthCheckServiceServer will
// result in compilation errors.
type UnsafeHealthCheckServiceServer interface {
	mustEmbedUnimplementedHealthCheckServiceServer()
}

func RegisterHealthCheckServiceServer(s grpc.ServiceRegistrar, srv HealthCheckServiceServer) {
	s.RegisterService(&HealthCheckService_ServiceDesc, srv)
}

func _HealthCheckService_CheckHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthCheckServiceServer).CheckHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthCheckService_CheckHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthCheckServiceServer).CheckHealth(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthCheckService_WatchHealth_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HealthCheckServiceServer).WatchHealth(m, &healthCheckServiceWatchHealthServer{stream})
}

type HealthCheckService_WatchHealthServer interface {
	Send(*HealthCheckResponse) error
	grpc.ServerStream
}

type healthCheckServiceWatchHealthServer struct {
	grpc.ServerStream
}

func (x *healthCheckServiceWatchHealthServer) Send(m *HealthCheckResponse) error {
	return x.ServerStream.SendMsg(m)
}

// HealthCheckService_ServiceDesc is the grpc.ServiceDesc for HealthCheckService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthCheckService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.v1.HealthCheckService",
	HandlerType: (*HealthCheckServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckHealth",
			Handler:    _HealthCheckService_CheckHealth_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchHealth",
			Handler:       _HealthCheckService_WatchHealth_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpc/v1/healthcheck.proto",
}
