name: Default workflow

on:
  push:
    branches-ignore:
      - main

jobs:
  go-lint:
    uses: ./.github/workflows/go.lint.action.yaml
    with:
      go_version: '1.22.x'
  go-test:
    uses: ./.github/workflows/go.test.action.yaml
    with:
      go_version: '1.22.x'
  go-build:
    needs: [ go-lint, go-test ]
    uses: ./.github/workflows/go.build.action.yaml