name: Dev workflow

on:
  push:
    branches:
      - dev

jobs:
  go-lint:
    uses: ./.github/workflows/go.lint.action.yaml
    with:
      go_version: '1.21.2'
  go-test:
    uses: ./.github/workflows/go.test.action.yaml
    with:
      go_version: '1.21.2'
  heroku:
    needs: [ go-lint, go-test ]
    uses: ./.github/workflows/heroku.build-push.action.yaml
    with:
      env_name: 'beta'
    secrets:
      heroku_api_key: ${{ secrets.HEROKU_API_KEY }}