name: Dev workflow

on:
  push:
    branches:
      - dev

jobs:
  go-lint:
    uses: ./.github/workflows/go.lint.action.yaml
    with:
      go_version: '1.22.x'
  go-test:
    uses: ./.github/workflows/go.test.action.yaml
    with:
      go_version: '1.22.x'
  go-build:
    needs: [ go-lint, go-test ]
    uses: ./.github/workflows/go.build.action.yaml
  docker-build-push:
    needs: [ go-build ]
    uses: ./.github/workflows/docker.build-push.action.yaml