name: Go - Build

on: workflow_call

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 'Generate build number'
        run: |
          BUILD_NUMBER=$(git rev-list --all --count)
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
          echo "This build is tagged as $BUILD_NUMBER on $GITHUB_REF"
      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: chabo-api:${{ github.sha }}
          outputs: type=docker,dest=/tmp/chabo-api-image.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: chabo-api-image
          path: /tmp/chabo-api-image.tar