name: Heroku - Build & Push

on: 
  workflow_call:
    inputs:
      env_name:
        description: 'Then env on which the app wil be executed (beta or prod)'
        required: true
        type: string
    secrets:
      heroku_api_key:
        description: 'Secret used to login against Heroku API'
        required: true

jobs:
  build-push:
    name: 'Build & Push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Generate version number
        run: |
          VERSION_NUMBER=$(git describe --always --long)
          echo "VERSION_NUMBER=$VERSION_NUMBER" >> $GITHUB_ENV
          echo "This VERSION is tagged as $VERSION_NUMBER on $GITHUB_REF"
      - name: Install Heroku
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - name: Login to Heroku
        run: heroku container:login
        env: 
          HEROKU_API_KEY: ${{ secrets.heroku_api_key }}
      - name: Build & Push to Heroku
        run: heroku container:push web --app chabo-api-${{ inputs.env_name }} --arg VERSION=${{ env.VERSION_NUMBER }}
        env: 
          HEROKU_API_KEY: ${{ secrets.heroku_api_key }}
      - name: Promote build to Heroku
        run: heroku container:release web --app chabo-api-${{ inputs.env_name }}
        env: 
          HEROKU_API_KEY: ${{ secrets.heroku_api_key }}