name: Main workflow

on:
  push:
    branches:
      - main

jobs:
  go-lint:
    uses: ./.github/workflows/go.lint.action.yaml
    with:
      go_version: '1.22.x'
    secrets: inherit
  go-test:
    uses: ./.github/workflows/go.test.action.yaml
    with:
      go_version: '1.22.x'
    secrets: inherit
  go-build:
    needs: [ go-lint, go-test ]
    uses: ./.github/workflows/go.build.action.yaml
    secrets: inherit
  docker-build-push:
    needs: [ go-build ]
    uses: ./.github/workflows/docker.build-push.action.yaml
    secrets: inherit